version: 2.1
defaults: &defaults
  docker:
    - image: node:lts-slim

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: apt-get update
      - run: export DEBIAN_FRONTEND="noninteractive"
      - run: apt-get install -y
                  build-essential
                  git
                  libsecret-1-dev
                  fakeroot
                  libx11-dev
                  libxkbfile-dev
                  libgdk-pixbuf2.0-dev
                  libgtk-3-dev
                  libxss-dev
                  libasound2-dev
                  libnss3
                  xvfb
      - run: yarn install || sleep 1 && yarn install || sleep 2 && yarn install ||  sleep 10 && yarn install
      - run: yarn run build
      - run: yarn run build:apm
      - run: Xvfb :99 & DISPLAY=:99 npx playwright test
      - store_artifacts:
          path: ./tests/videos

workflows:
  version: 2
  default-workflow:
    jobs:
      - test
