jobs:
  - job: Lint
    timeoutInMinutes: 10
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          cd script
          npm ci
        displayName: Install script dependencies
      - script: node ./script/lint.js
        displayName: Run linter
