name: Editor tests
on:
  - push
  - pull_request
jobs:
  tests:
    name: tests
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3.0.2

    - name: Setup node
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2.2.2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, prettier, gulp]

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
    - name: Build VuePress Site
      run: pnpm build

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: pnpm start --test spec
