name: Package tests for Pulsar

env:
  DEBUG: electron-rebuild

on:
  - push
  - pull_request
jobs:
  tests:
    name: tests
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install windows-build-tools
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        npm i --global windows-build-tools@4.0.0
        npm config set msvs_version 2019

    - name: Checkout the latest code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16

    - name: install dependencies
      run: yarn install

    - name: build dependencies
      run: yarn build

    - name: Run the tests on sane OSes
      uses: GabrielBB/xvfb-action@v1
      if: ${{ !contains(matrix.os, 'windows') }}
      with:
        run: node script/run-package-tests.js

    - name: Run the tests on Windows
      if: ${{ contains(matrix.os, 'windows') }}
      continue-on-error: true # due to https://github.com/atom/github/pull/2459#issuecomment-624725972
      run: node script\run-package-tests.js
